### ISSUE TITLE
Support for install

### ISSUE THREAD

**Issue by knute-mips** [sparcians/stf_tools#4]
It would be super mega aweomely cool if this repo had install support.  😄

**Comment by bdutro** [comment]
It does! Just set `-DSTF_INSTALL_DIR=<path/to/install/dir>` when you run cmake and it will enable the install target.

**Comment by knute-mips** [comment]
Neat!

**Comment by knute-mips** [comment]
This works:
```
$ cmake  .. -DSTF_INSTALL_DIR=$CONDA_PREFIX/bin
$ make install
```
