### ISSUE TITLE
stf_check seg faults on core mark trace in Olympia

### ISSUE THREAD

**Issue by knute-mips** [sparcians/stf_tools#5]
How to reproduce:

- Clone https://github.com/riscv-software-src/riscv-perf-model
-  Run `stf_check /riscv-perf-model/traces/core_riscv.zstf`

```
Trace generator: Dromajo
Trace generator version: 1.1.0
Comment: Trace from Dromajo
Features: 0000000000080021
Segmentation fault (core dumped)
```

**Comment by knute-mips** [comment]
I expect this trace to be no good, but I was hoping the tool would tell me that.  😉

**Comment by bdutro** [comment]
Fixed in https://github.com/sparcians/stf_lib/pull/25
