### ISSUE TITLE
Register REG_24 not present in the map

### ISSUE THREAD

**Issue by danbone** [sparcians/stf_tools#6]
Hi,

Trying to use the stf_branch_dump tool on the example trace included in the Olympia repo and I'm hitting this error.

Any idea what could be the problem?

```
./stf_branch_dump ~/riscv-perf-model/traces/dhry_riscv.zstf 
terminate called after throwing an instance of 'stf::STFException'
  what():  abort: Register REG_24 not present in the map: in file: '/home/dan/stf_tools/stf_lib/stf-inc/stf_branch.hpp', on line: 69
Aborted
```

**Comment by bdutro** [comment]
Yes, unfortunately that trace doesn't include operand values. I'll update the error message to something more useful. In the meantime, you can try the traces in https://github.com/kathlenemagnus/condor_dromajo/tree/kathlenemagnus/stf_improvements/tests/stf_gen/golden

**Comment by danbone** [comment]
Out of interest why are the operand values necessary?

**Comment by bdutro** [comment]
That's actually a really good point - they're used in stf_branch_hdf5, but even then I wouldn't consider that "required". I'll just have the library default to 0 if it doesn't have an operand data.

**Comment by bdutro** [comment]
It should work now if you pull the latest master.
